### ISSUE TITLE
Build a proper installer

### ISSUE THREAD

**Issue by hjlinde** [Rainbox-dev/Duik#212]
Please create a proper OS X pkg installer. Using custom tools (e.g writing your own install app) cause issues with mass deployment of the plugin which really should not be the case. An installer should be able to run at the loginwindow.

As a sysadmin, we don't really want to do your work for you...

**Comment by Nico-Duduf** [comment]
> As a sysadmin, we don't really want to do your work for you...

Creating an installer, and even developping Duik, is NOT my work. It's something done in my spare time, I don't make any revenue with it.
I just don't know how to create a proper installer for OSX, I don't have time to learn it, and I provided all infos needed to install Duik manually, so a sysadmin could build his own mass deployment.

After all, Duik is free and open source, YOU can help by building tools needed to improve it, instead of just stating what should or shouldn't created.

**Comment by Nico-Duduf** [comment]
not needed in Duik16 which is just one file to copy.
