### ISSUE TITLE
occur at line 3984 on macOS 10.12/ AE 14.2.1 

### ISSUE THREAD

**Issue by msongz** [Rainbox-dev/Duik#390]
when using wiggle or spring
After Effects error: Can not add a property with name “PSEUDO/DUIK_Spring” to this PropertyGroup.

**Comment by Nico-Duduf** [comment]
This is a bug which happens when Duik is incorrectly installed: you'll have to follow the manual installation procedure (see in the user guide), happens sometimes on Mac OS.

The installation will be different in Duik 16, available soon, which will use a different procedure and fix those bugs once and for all.
